# Generated by Django 5.1.1 on 2024-09-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="candidate",
        ),
        migrations.AddField(
            model_name="application",
            name="email",
            field=models.EmailField(default="Unknown", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="first_name",
            field=models.CharField(default="Applicant", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="last_name",
            field=models.CharField(default="Applicant", max_length=100),
            preserve_default=False,
        ),
    ]
