# Generated by Django 5.1.1 on 2024-09-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0005_remove_application_candidate_application_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="country_code",
            field=models.CharField(default="+1", max_length=5),
        ),
        migrations.AddField(
            model_name="application",
            name="interested_in_account",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="application",
            name="mobile_number",
            field=models.CharField(default="+1", max_length=15),
            preserve_default=False,
        ),
    ]
