# Generated by Django 5.1.1 on 2024-10-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0007_application_candidate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("job", "email")},
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("applied", "Applied"),
                    ("in_review", "In Review"),
                    ("interview", "Interview Scheduled"),
                    ("hired", "Hired"),
                    ("rejected", "Rejected"),
                ],
                default="applied",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="application",
            name="candidate",
        ),
    ]
