# Generated by Django 5.1.1 on 2024-09-10 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0002_alter_job_recruiter"),
        ("recruiter", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Recruiter",
        ),
    ]
