# Generated by Django 5.1.1 on 2024-09-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0005_user_groups_user_user_permissions_alter_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
